{{- if and .Values.minecraftServer.monitor.enabled .Values.minecraftServer.monitor.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "minecraft.fullname" . }}
{{- if .Values.minecraftServer.monitor.servicemonitor.namespace }}
  namespace: {{ .Values.minecraftServer.monitor.servicemonitor.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    prometheus: {{ .Values.minecraftServer.monitor.servicemonitor.prometheusInstance }}
{{- if .Values.minecraftServer.monitor.servicemonitor.labels }}
{{ toYaml .Values.minecraftServer.monitor.servicemonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: {{ template "minecraft.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "minecraft.fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: {{ .Values.minecraftServer.monitor.servicemonitor.targetPort }}
    path: {{ .Values.minecraftServer.monitor.servicemonitor.path }}
    interval: {{ .Values.minecraftServer.monitor.servicemonitor.interval }}
    scrapeTimeout: {{ .Values.minecraftServer.monitor.servicemonitor.scrapeTimeout }}
{{- end }}